version: '3.9'

services:
    web:
        image: nginx:latest
        container_name: git-web
        ports:
            - '80:80'
        volumes:
            - ./:/var/www/html
            - ./config/default.conf:/etc/nginx/conf.d/default.conf

    app:
        build:
            context: ./config
        container_name: git-app
        volumes:
            - ./:/var/www/html
        ports:
            - "9000:9000"